# Generated by Django 5.1.6 on 2025-02-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_rename_phone_number_user_phone_remove_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('delivery_person', 'Delivery Person'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
