# Generated by Django 5.1.6 on 2025-02-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('appliances', 'Kitchen Appliances'), ('Cookware', 'Cookware'), ('utensils', 'Utensils'), ('storage', 'Storage & Containers'), ('cleaning', 'Cleaning Supplies')], default='Cookware', max_length=255),
        ),
    ]
