# Generated by Django 5.1.6 on 2025-03-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_cart_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
