# Generated by Django 5.1.6 on 2025-03-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('delivery_person', 'Delivery Person'), ('customer', 'Customer')], default='admin', max_length=20),
        ),
    ]
