# Generated by Django 5.1.6 on 2025-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0017_deliveryperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Out of Delivery', 'Out of Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
    ]
