# Generated by Django 5.1.6 on 2025-03-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0018_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
